/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author zeeshan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_P = new javax.swing.JPanel();
        date_L = new javax.swing.JLabel();
        stocks_L1 = new javax.swing.JLabel();
        Main_P = new javax.swing.JPanel();
        stock_P = new javax.swing.JPanel();
        selectcrypto_CB1 = new javax.swing.JComboBox<>();
        stock_P1 = new javax.swing.JPanel();
        selectstock_CB2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stocks Main");

        Title_P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        date_L.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        date_L.setText("Date");

        stocks_L1.setFont(new java.awt.Font("Dialog", 2, 36)); // NOI18N
        stocks_L1.setText("STOCKS & CRYPTO");

        javax.swing.GroupLayout Title_PLayout = new javax.swing.GroupLayout(Title_P);
        Title_P.setLayout(Title_PLayout);
        Title_PLayout.setHorizontalGroup(
            Title_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Title_PLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(stocks_L1)
                .addGap(224, 224, 224)
                .addComponent(date_L, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Title_PLayout.setVerticalGroup(
            Title_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_PLayout.createSequentialGroup()
                .addGroup(Title_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Title_PLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(date_L))
                    .addGroup(Title_PLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(stocks_L1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Main_P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        stock_P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        selectcrypto_CB1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        selectcrypto_CB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Crypto", "crypto1", "crypto2", "crypto3", "crypto4", "crypto5" }));

        javax.swing.GroupLayout stock_PLayout = new javax.swing.GroupLayout(stock_P);
        stock_P.setLayout(stock_PLayout);
        stock_PLayout.setHorizontalGroup(
            stock_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stock_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectcrypto_CB1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        stock_PLayout.setVerticalGroup(
            stock_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stock_PLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(selectcrypto_CB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        stock_P1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        selectstock_CB2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        selectstock_CB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Stock", "stock1", "stock2", "stock3", "stock4", "stock5" }));

        javax.swing.GroupLayout stock_P1Layout = new javax.swing.GroupLayout(stock_P1);
        stock_P1.setLayout(stock_P1Layout);
        stock_P1Layout.setHorizontalGroup(
            stock_P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stock_P1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectstock_CB2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );
        stock_P1Layout.setVerticalGroup(
            stock_P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stock_P1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(selectstock_CB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Main_PLayout = new javax.swing.GroupLayout(Main_P);
        Main_P.setLayout(Main_PLayout);
        Main_PLayout.setHorizontalGroup(
            Main_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_PLayout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(stock_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Main_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Main_PLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(stock_P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(482, Short.MAX_VALUE)))
        );
        Main_PLayout.setVerticalGroup(
            Main_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stock_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Main_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_PLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(stock_P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Main_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(Main_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_P;
    private javax.swing.JPanel Title_P;
    private javax.swing.JLabel date_L;
    private javax.swing.JComboBox<String> selectcrypto_CB1;
    private javax.swing.JComboBox<String> selectstock_CB2;
    private javax.swing.JPanel stock_P;
    private javax.swing.JPanel stock_P1;
    private javax.swing.JLabel stocks_L1;
    // End of variables declaration//GEN-END:variables
}
