package GUI;

// importing API package to call methods in GUI class.
import API.*;
import Data_Proccessing.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;

/**
 *
 * @author zeeshan
 */
public class Main extends javax.swing.JFrame {

    // arrtributes and class calls from different packages
    API_Connect API = new API_Connect();
    Validation validate = new Validation();
    ImageIcon icon = new ImageIcon("java/Assets/logo_uni.png");

    // time 
    String current_time = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        date_L.setText("Date: " + current_time);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_P = new javax.swing.JPanel();
        date_L = new javax.swing.JLabel();
        stocks_L1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        stock_CB = new javax.swing.JComboBox<>();
        clear_B = new javax.swing.JButton();
        show_B1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stock_T = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        crypto_CB = new javax.swing.JComboBox<>();
        clear_B1 = new javax.swing.JButton();
        show_B2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        crypto_T = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stocks Main");

        Title_P.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        date_L.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        date_L.setText("Date");

        stocks_L1.setFont(new java.awt.Font("Dialog", 2, 36)); // NOI18N
        stocks_L1.setText("STOCKS & CRYPTO");

        javax.swing.GroupLayout Title_PLayout = new javax.swing.GroupLayout(Title_P);
        Title_P.setLayout(Title_PLayout);
        Title_PLayout.setHorizontalGroup(
            Title_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_PLayout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(stocks_L1)
                .addGap(256, 256, 256)
                .addComponent(date_L, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Title_PLayout.setVerticalGroup(
            Title_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_PLayout.createSequentialGroup()
                .addGroup(Title_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Title_PLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(date_L))
                    .addGroup(Title_PLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(stocks_L1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        stock_CB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stock_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Stock", "GOOG", "TSLA", "AAPL", "AMZN", "XOM", "GOLD", "V", "ASML", "GM", "GE", "PG", "GS", "AG", "GT", "GD", "DG", "AGG", "BG", "GGB", "CG", "GGE", "NG", "GH", "NGG", "GGR", "SG", "ZG", "GP", "GGN", "GO", "UG", "GSG", "GGG", " " }));
        stock_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_CBActionPerformed(evt);
            }
        });

        clear_B.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clear_B.setText("Clear");
        clear_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BActionPerformed(evt);
            }
        });

        show_B1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        show_B1.setText("Show");
        show_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_B1ActionPerformed(evt);
            }
        });

        stock_T.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stock_T.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stock_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Currency", "Exchange", "Price", "Change", "Volume", "Statistics", "Dividend"
            }
        ));
        stock_T.setEnabled(false);
        jScrollPane1.setViewportView(stock_T);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stock_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear_B)
                    .addComponent(show_B1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(218, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stock_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_B1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear_B, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        crypto_CB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        crypto_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Crypto", "BTC-USD", "ETH-USD", "USDT-USD", "USDC-USD", "BNB-USD", "XRP-USD", "BUSD-USD", "ADA-USD", "SOL-USD", "DOGE-USD", "MATIC-USD", "DOT-USD", "DAI-USD", "WTRX-USD", "SHIB-USD", "HEX-USD" }));

        clear_B1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clear_B1.setText("Clear");
        clear_B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_B1ActionPerformed(evt);
            }
        });

        show_B2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        show_B2.setText("Show");
        show_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_B2ActionPerformed(evt);
            }
        });

        crypto_T.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        crypto_T.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        crypto_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Currency", "Exchange", "Price", "Change", "Volume", "Statistics", "Dividend"
            }
        ));
        jScrollPane2.setViewportView(crypto_T);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crypto_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear_B1)
                    .addComponent(show_B2))
                .addContainerGap(930, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(218, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crypto_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_B2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title_P, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_B1ActionPerformed
        API.GetStock(stock_CB, stock_T);
    }//GEN-LAST:event_show_B1ActionPerformed

    private void stock_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_CBActionPerformed

    private void clear_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BActionPerformed
        validate.Clear(stock_T);
    }//GEN-LAST:event_clear_BActionPerformed

    private void show_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_B2ActionPerformed
        API.GetCrypto(crypto_CB, crypto_T);
    }//GEN-LAST:event_show_B2ActionPerformed

    private void clear_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_B1ActionPerformed
        validate.Clear(crypto_T);
    }//GEN-LAST:event_clear_B1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {
        setIconImage(icon.getImage());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Title_P;
    private javax.swing.JButton clear_B;
    private javax.swing.JButton clear_B1;
    private javax.swing.JComboBox<String> crypto_CB;
    private javax.swing.JTable crypto_T;
    private javax.swing.JLabel date_L;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton show_B1;
    private javax.swing.JButton show_B2;
    private javax.swing.JComboBox<String> stock_CB;
    private javax.swing.JTable stock_T;
    private javax.swing.JLabel stocks_L1;
    // End of variables declaration//GEN-END:variables
}
